pipeline {
    agent any
    
    tools {
        nodejs "Node14" 
    }
    
    stages {
        

        stage('React build') {
            steps {
                dir('FE') {
                    echo 'React build'
                    sh 'npm install' 
                    sh 'CI=false NODE_OPTIONS="--max_old_space_size=1024" npm run build'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('FE') {
                    sh '''
                    echo 'Dockerimage build for React'
                    docker build -t docker-react:0.0.1 .
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                echo 'Deploy React'
                docker stop react
                docker rm react
                docker run -d -p 3000:3000 --name react docker-react:0.0.1 

                '''
            }
        }
    }
}